### ISSUE TITLE
Generic fallback image

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-avatar#13]
# General Support Request

Currently, auro-avatar only supports when a code is not given and it points to SEA. There is no support for a 404 request. 

## Support request

Update the element to support a new generic image for both cases of non-entry and 404.

https://resource.alaskaair.net/-/media/Images/common-assets/destinations/180x180/partner
https://resource.alaskaair.net/-/media/Images/common-assets/destinations/360x360/partner
https://resource.alaskaair.net/-/media/Images/common-assets/destinations/800x800/partner

Expose 404 error event

having a fall back will fix #16

**Comment by blackfalcon** [comment]
Increased use has exposed an issue where new destinations are being requested prior to avatar art being created. Having a consistent fallback is needed.

**Comment by gusnaughton** [comment]
@blackfalcon  how is the art supposed to be created, and once it is, how is it supposed to be uploaded to Auro's CDN?

**Comment by gusnaughton** [comment]
@jason-capsule42  how will this be implemented? Kayla Blyton spent some time last year making fallback images per region, depending on the station requested. There is a hook for this in the component hangar (resolving a station name to a region). Please let me know if this makes sense.

**Comment by gusnaughton** [comment]
https://www.figma.com/file/y85boLCDQxxyYfgBourkaw/Partner-Destination-Images?node-id=0%3A1

**Comment by gusnaughton** [comment]
From Kayla: 
Link to the 180x 180 image for BZE (media library -> images -> common assets -> destinations -> partner destinations -> 180 x 180 -> BZE):
https://cms.alaskaair.com/sitecore/shell/Applications/Content%20Manager/default.aspx?he=Media+Library&pa=1&ic=Applications%2f16x16%2fphoto_scenery.png&mo=media&ro={3D6658D8-A0BF-4E75-B3E2-D050FABCF4E1}&sc_bw=1
Link to the 180 x 180 image for MEX - 'Central America' is the generic image for this region (media library -> images -> common assets -> destinations -> partner destinations -> 180 x 180 -> Central America)https://cms.alaskaair.com/sitecore/shell/Applications/Content%20Manager/default.aspx?he=Media+Library&pa=1&ic=Applications%2f16x16%2fphoto_scenery.png&mo=media&ro={3D6658D8-A0BF-4E75-B3E2-D050FABCF4E1}&sc_bw=1


I have trouble getting links to point to specific locations in SC8, so I provided the path too. In the "Partner Images" folder there are files for all the other image sizes.



Figma File with all final images and associated regions: https://www.figma.com/file/y85boLCDQxxyYfgBourkaw/Partner-Destination-Images?node-id=403%3A7695

**Comment by blackfalcon** [comment]
@gusnaughton the idea we had was to try the URL from the requested image code and if that returns a 404 then insert a fallback image. The idea here is that we need to guard ourselves against any new destination that an avatar has not been created for yet. And when that avatar is created, then it will be used. 

Your hooks are for specific endpoints, right? Why do we not have an image avatar for BZE or MEX? I don't really want to get into the business of maintaining an alias list of avatar endpoints.
