### ISSUE TITLE
Destination images used for Flight Status were set at 165x165 in Figma

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-avatar#15]
Hi, Dale! The final destination images used for Flight Status were set at 165x165 in Figma. Here's a screenshot of the final design in the wild (which looks like it scaled to 226x226):

<img width="434" alt="Screen Shot 2021-09-17 at 10 24 42 AM" src="https://user-images.githubusercontent.com/80366631/133829222-5e32637e-90f0-47ac-a2af-fa6c934bd888.png">

_Originally posted by @KyleJones2 in https://github.com/AlaskaAirlines/auro-avatar/issues/6#issuecomment-921962486_

**Comment by blackfalcon** [comment]
@KyleJones2 you are correct, but this is not an issue with auro-avatar, see the attached screenshot. The size is being set in the app code. Please discuss this with your engineering team. 
<img width="1450" alt="Screen Shot 2021-09-17 at 11 16 53 AM" src="https://user-images.githubusercontent.com/181089/133835439-034e9008-5b31-49c2-be1e-27ebac2ab00e.png">

**Comment by KyleJones2** [comment]
Okay, thank you for clarifying.
