### ISSUE TITLE
auro-avatar: figma component

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-avatar#18]
# Figma component
We need a Figma component for auro-avatar that matches the features we have currently on our doc site.

## Outline tasks

- [x] Figma instructions
- [x] Component descriptions
- [x] Pressure testing for flexibility
- [x] Doc site review
- [ ] Release notes
- [ ] Publish

**Comment by leeejune** [comment]
https://www.figma.com/file/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?node-id=2339%3A14509

Component done. Will publish after review.

**Comment by blackfalcon** [comment]
@leeejune :shipit:
