### ISSUE TITLE
auro-avatar: review bundle size

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-avatar#32]
## Describe the bug

With the last release of auro-avatar, the bundled version of the element grew in size. Compare the following links. 

https://www.runpkg.com/?@aurodesignsystem/auro-avatar@4.2.1/index.js

https://www.runpkg.com/?@aurodesignsystem/auro-avatar@4.2.2/index.js

## Expected behavior

Either the bundle size should not grow in size, or there needs to be a reason why it's larger. 

## Exit criteria 

Review the difference between v4.2.1 and v4.2.2 and revert the new size increase or provide a reason why this is not a problem.

**Comment by blackfalcon** [comment]
After some research, I believe this is an issue due to the removal of an unsupported 

See the following notes on this issue 

- https://github.com/AlaskaAirlines/WC-Generator/issues/181

**Comment by Patrick-Daly-AA** [comment]
note: will migrate this issue to the WC-Generator repository to fix this more broadly.
