### ISSUE TITLE
Custom images are not loading on API page

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-avatar#55]
### Please verify the version of auro-avatar you have installed

4.5.1

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/avatar/api
2. Scroll to "Custom images" example
3. See error (images are not loading)

<img width="1342" alt="Screen Shot 2024-06-06 at 11 31 23 AM" src="https://github.com/AlaskaAirlines/auro-avatar/assets/55807669/578394dd-7d89-4470-9382-8feef09fb0f0">

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### Expected behavior

Custom images are loading

### What browsers are you seeing the problem on?

Chrome

**Comment by Patrick-Daly-AA** [comment]
Issue no longer occurs.  Was most likely caused by outage or hiccup on external image source.
