### ISSUE TITLE
Review new token usage

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-avatar#58]
### Please describe the bug

The new beta release has the updated tokens but the values set need to be reviewed.

```
@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables';

:host {
  --ds-auro-avatar-tail-container-gradient-color-one: var(--ds-color-brand-navy-500, #{$ds-color-brand-navy-500});
  --ds-auro-avatar-tail-container-gradient-color-two: rgba(255 255 255 / .9);
}
```

### Reproducing the error on the docsite

None

### Expected behavior

We should not be using any tier1 token nor any hard coded values

**Comment by leeejune** [comment]
Reviewed in a meeting with @jordanjones243.
