### ISSUE TITLE
Reference appropriate endpoint for avatar size

### ISSUE THREAD

**Issue by KyleJones2** [AlaskaAirlines/auro-avatar#6]
## Is your feature request related to a problem? Please describe.
The small and medium size is too small for the flight status designs.

## Describe the solution you'd like
Requesting a large avatar siz (225 px)

## Describe alternatives you've considered
I considered the small and medium size but decided a large would be a better fit. 

## Additional context
[https://www.figma.com/file/tPJKavRLJnw8Nl3DPBvCKp/Flight-Status-2.0?node-id=290%3A1138](url)

The component needs to support the correct size cut when requested for the avatar. Right now the avatar is pulling from a single bucket of images. 

180x180: https://resource.alaskaair.net/-/media/Images/common-assets/destinations/180x180/hnl
360x360: https://resource.alaskaair.net/-/media/Images/common-assets/destinations/360x360/hnl
800x800: https://resource.alaskaair.net/-/media/Images/common-assets/destinations/800x800/hnl

https://resource.alaskaair.net/-/media/Images/common-assets/destinations/180x180/hnlresource.alaskaair.net

**Comment by blackfalcon** [comment]
Either there was a massive regression or this was never done? Reopening for review.

**Comment by KyleJones2** [comment]
Hi, Dale! The final destination images used for Flight Status were set at 165x165 in Figma. Here's a screenshot of the final design in the wild (which looks like it scaled to 226x226):

<img width="434" alt="Screen Shot 2021-09-17 at 10 24 42 AM" src="https://user-images.githubusercontent.com/80366631/133829222-5e32637e-90f0-47ac-a2af-fa6c934bd888.png">

**Comment by blackfalcon** [comment]
> Hi, Dale! The final destination images used for Flight Status were set at 165x165 in Figma. Here's a screenshot of the final design in the wild (which looks like it scaled to 226x226):
> 
> <img alt="Screen Shot 2021-09-17 at 10 24 42 AM" width="434" src="https://user-images.githubusercontent.com/80366631/133829222-5e32637e-90f0-47ac-a2af-fa6c934bd888.png">

I moved this to a new issue. This issue is to be closed.
